stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build

  script:
    - npm install
    - npm run build
    - cd dist
    - tar cvfz ~/ngipf.tgz ngipf 
    - printf 'krish@Nic24\ny'|/opt/cisco/anyconnect/bin/vpn -s connect sconnect.nic.in
    - scp ~/ngipf.tgz root@10.173.13.51:/usr/share/nginx/html/
    - ssh root@10.173.13.51 "cd /usr/share/nginx/html/ && rm -rf ngipf && tar xvfz ngipf.tgz && rm ngipf.tgz && chown -R root:root ngipf &&chmod -R 755 ngipf && systemctl stop nginx && systemctl daemon-reload && systemctl start nginx"
    - /opt/cisco/anyconnect/bin/vpn disconnect
